### ISSUE TITLE
Kamelot crashed when requesting cores resources

### ISSUE THREAD

**Issue by SalemHarrache** [oar-team/oar-kao#1]
I tried to do a simple job submission with one core as a resource but Kamelot crashed with the following traceback
```
frontend>$ oarsub -l core=1 -I
```

```
[debug] [2016-01-11 22:44:12.487] [MetaSched] Queue default: Launching scheduler kamelot at time 2016-01-11 22:44:13
[   DEBUG] [2016-01-11 22:44:12,782] [oar.kamelot]: argv...['/usr/local/lib/oar//schedulers/kamelot', 'default', '1452548653', '2016-01-11 22:44:13']
[    INFO] [2016-01-11 22:44:12,782] [oar.kamelot]: Begin scheduling....now: 1452548653, queue: default
[    INFO] [2016-01-11 22:44:12,867] [oar.kamelot]: nb_waiting_jobs:1
[   DEBUG] [2016-01-11 22:44:12,867] [oar.kamelot]: waiting_jid: 1
[   DEBUG] [2016-01-11 22:44:12,946] [oar.kamelot]: Schedule job:1
Traceback (most recent call last):
  File "/usr/local/lib/oar//schedulers/kamelot", line 9, in <module>
    load_entry_point('oar-kao', 'console_scripts', 'kamelot')()
  File "/oar-python/kao/oar/kao/kamelot.py", line 195, in main
    schedule_cycle(plt, int(float(sys.argv[2])), sys.argv[1])
  File "/oar-python/kao/oar/kao/kamelot.py", line 170, in schedule_cycle
    job_security_time)
  File "/oar-python/kao/oar/kao/scheduling.py", line 316, in schedule_id_jobs_ct
    assign_resources_mld_job_split_slots(slots_set, job, hy, min_start_time)
  File "/oar-python/kao/oar/kao/scheduling.py", line 226, in assign_resources_mld_job_split_slots
    slots_set, job, res_rqt, hy, min_start_time)
  File "/oar-python/kao/oar/kao/scheduling.py", line 185, in find_first_suitable_contiguous_slots
    itvs = find_resource_hierarchies_job(itvs_avail, hy_res_rqts, hy)
  File "/oar-python/kao/oar/kao/scheduling.py", line 85, in find_resource_hierarchies_job
    hy_levels.append(hy[l_name])
KeyError: u'core'
```

```
> /oar-python/kao/oar/kao/scheduling.py(86)find_resource_hierarchies_job()
-> hy_levels.append(hy[l_name])
(Pdb) hy_levels
[]
(Pdb) hy
{'network_address': [[(0, 7)], [(8, 15)], [(16, 23)]], 'resource_id': [[(0, 0)], [(1, 1)], [(2, 2)], [(3, 3)], [(4, 4)], [(5, 5)], [(6, 6)], [(7, 7)], [(8, 8)], [(9, 9)], [(10, 10)], [(11, 11)], [(12, 12)], [(13, 13)], [(14, 14)], [(15, 15)], [(16, 16)], [(17, 17)], [(18, 18)], [(19, 19)], [(20, 20)], [(21, 21)], [(22, 22)], [(23, 23)]]}
```

```
-> res_set, sid_left, sid_right = find_first_suitable_contiguous_slots(
(Pdb) job.mld_res_rqts
[(1L, 7260, [([(u'core', 1)], [(0, 23)])])]
```

**Comment by augu5te** [comment]
Seems configuration issue, does HIERARCHY_LABEL variable have core in the provided list ?

**Comment by SalemHarrache** [comment]
OK, it seems this is what's causing the issue.

However, in the conf file oar.conf, the (commented) variable is called:
```
#HIERARCHY_LABELS="resource_id,network_address,cpu,core"
```
Whereas it's called HIERARCHY_LABEL in the code.

So, should we correct the conf file?

**Comment by augu5te** [comment]
Plural seems more adequate here for me, we can change source code.
